"""Add prior ratings and rating changes to game model

Revision ID: 79a6492612b5
Revises: 
Create Date: 2024-09-25 10:59:21.798104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a6492612b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prior_rating_player1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prior_rating_player2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_change_player1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_change_player2', sa.Integer(), nullable=False))
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('rating_change_player2')
        batch_op.drop_column('rating_change_player1')
        batch_op.drop_column('prior_rating_player2')
        batch_op.drop_column('prior_rating_player1')

    # ### end Alembic commands ###
