"""Add is_active field to Player

Revision ID: ca5da6b1d406
Revises: a82a7bbe01a3
Create Date: 2024-10-02 10:12:47.163067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5da6b1d406'
down_revision = 'a82a7bbe01a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
